<?php

/**
 * @file
 * Checks text against multiple filters to ascertain spamminess
 */

/**
 * Implements hook_spam_detect().
 */
function spam_detect_composite_spam_detect($text, $context) {
	$links_array = spam_detect_composite_find_links($text);
	$spam_threshold = variable_get('spam_detect_composite_score_threshold');
	$spam_score = array();

	$spam_score[] = spam_detect_composite_links_in_body_score($links_array[0]);
	$spam_score[] = spam_detect_composite_body_length_score($text);
	$spam_score[] = spam_detect_composite_consonants($text);
	$spam_score[] = spam_detect_composite_first_word($text);

	dd($spam_score);
	$spam_score = array_sum($spam_score);

	if ($spam_score > 0) {
		if (($spam_score / $spam_threshold) > 1) {
			return 1;
		} 
		else {
			return $spam_score / $spam_threshold;
		}
	}
	
	return 0;
}


function spam_detect_composite_links_in_body_score($links_array) {

	$link_count = count($links_array);

	$threshold = variable_get('spam_detect_composite_link_body_count');

	$decrease  = variable_get('spam_detect_composite_body_length_decrease_spamminess');
	$increase = variable_get('spam_detect_composite_link_body_count_increase_spamminess');

 	if ($threshold < 0) { 
		$spam_score = 0; // Filter is set to off: -1
	} 
	elseif ($link_count < $threshold) {
		$spam_score = -$decrease;
	}
	elseif ($link_count >= $threshold) {
		$spam_score = $link_count * $increase;
	} 
	return $spam_score;
}

function spam_detect_composite_body_length_score($text) {
	$threshold = variable_get('spam_detect_composite_body_length_threshold');
	$length = strlen($text);
	$decrease = variable_get('spam_detect_composite_body_length_decrease_spamminess');
	$increase = variable_get('spam_detect_composite_body_length_increase_spamminess');

	if ($threshold < 0) {
		$spam_score = 0; // Filter is set to off: -1
	}
	elseif ($length > $threshold) {
		$spam_score = -$decrease;
	} 
	else {
		$spam_score = $increase;
	}

	return $spam_score;
}

function spam_detect_composite_consonants($text) {
	// check for more than 5 consonants in a row
	// 
	$increase = variable_get('spam_detect_composite_consonants_increase');
	preg_match_all('/[bcdfghjklmnpqrstvwxz]{6}/i', $text, $matches);  // matches 6 or mor
	
	if ($increase < 0) {
		$spam_score = 0; // Filter set to off: -1
	}
	else {
		$spam_score = count($matches[0]) * $increase;
	}

	return $spam_score;
}

function spam_detect_composite_first_word($text) {
	$increase = variable_get('spam_detect_composite_first_word_increase');

	$spammy_words = strtolower(variable_get('spam_detect_composite_first_word_list'));	
	$spammy_words = array_map('trim', explode("\n", $spammy_words));

	$first_word = strtolower(strtok($text, ' '));
	$first_word = preg_replace('/[^A-Za-z0-9\-]/', '', $first_word); // remove special chars





	if ($increase < 0){
		return 0; // filter set to off 
	} 
	elseif (in_array($first_word, $spammy_words)) {
		return $increase;
	}
	return 0;
} 

function _spam_detect_composite_first_word_list() {
	return <<<EOT
Interesting
Sorry
Nice
Cool
EOT;
}


function spam_detect_composite_find_links($text) {

	// Regex by John Gruber: http://daringfireball.net/2010/07/improved_regex_for_matching_urls
	// License: Public Domain
	$regex = '~(?i)\b((?:https?://|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:\'".,<>?«»“”‘’]))~';

	preg_match_all($regex, $text, $links_array);

	return $links_array;
} 

/**
 * Implements hook_menu().
 */
function spam_detect_composite_menu() {
  return array('admin/config/system/spam_detect/composite' => array(
    'title' => 'Composite',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('spam_detect_composite_settings_form'),
    'access arguments' => array('administer spam filter'),
  ));
}

/**
 * Settings form callback.
 * @todo Need to group the items together or put them on seperate tabs.
 */
function spam_detect_composite_settings_form() {
	$form = array();

	$form['spam_detect_composite_score_threshold'] = array(
    '#type' => 'textfield',
    '#title' => t('Composite Score Threshold'),
    '#description' => t('Sum of all active filters is divided by this threshold'),
    '#default_value' => variable_get('spam_detect_composite_score_threshold', 15),
    '#max_length' => 2,
    '#size'				=> 2,
  );

	$form['spam_detect_composite_link_body_count'] = array(
    '#type' => 'textfield',
    '#title' => t('Link Count in Body: Threshold'),
    '#description' => t('If link count in text is greater than this number then increase spamminess score.  If lower, decrease spamminess score. Set this to -1 to disable this filter.'),
    '#default_value' => variable_get('spam_detect_composite_link_body_count', 2),
    '#max_length' => 2,
    '#size'				=> 2,
  );

  	$form['spam_detect_composite_link_body_count_decrease_spamminess'] = array(
			'#title' 					=> t('Link Count in Body: Decrease Spamminess Score'),
			'#description' 		=> t('Amount to decrease spamminess if link count < threshold.'),
			'#default_value' 	=> variable_get('spam_detect_composite_link_body_count_decrease_spamminess', 2),
			'#type' 					=> 'textfield',
			'#max_length' 		=> 2,
			'#size'						=> 2,

	);

 	$form['spam_detect_composite_link_body_count_increase_spamminess'] = array(
			'#title' 					=> t('Link Count in Body: Increase Spamminess Score'),
			'#description' 		=> t('Amount to increase spamminess per link if link count > threshold.'),
			'#default_value' 	=> variable_get('spam_detect_composite_link_body_count_increase_spamminess', 1),
			'#type' 					=> 'textfield',
			'#max_length' 		=> 2,
			'#size'						=> 2,

	);

 	$form['spam_detect_composite_body_length_threshold'] = array(
			'#title' 					=> t('Body Length: Threshold'),
			'#description' 		=> t('Minimum character threshold to be consiered a good comment. Set to -1 to disable'),
			'#default_value' 	=> variable_get('spam_detect_composite_body_length_threshold', 20),
			'#type' 					=> 'textfield',
			'#max_length' 		=> 2,
			'#size'						=> 2,

	);

	$form['spam_detect_composite_body_length_increase_spamminess'] = array(
				'#title' 					=> t('Body Length: Increase Spamminess Score'),
				'#description' 		=> t('Amount to increase Spam Score by if Body Length < Threshold'),
				'#default_value' 	=> variable_get('spam_detect_composite_body_length_increase_spamminess', 1),
				'#type' 					=> 'textfield',
				'#max_length' 		=> 2,
				'#size'						=> 2,

		);

	$form['spam_detect_composite_body_length_decrease_spamminess'] = array(
				'#title' 					=> t('Body Length: Decrease Spamminess Score'),
				'#description' 		=> t('Amount to decrease Spam Score by if Body Length > Threshold'),
				'#default_value' 	=> variable_get('spam_detect_composite_body_length_decrease_spamminess', 2),
				'#type' 					=> 'textfield',
				'#max_length' 		=> 2,
				'#size'						=> 2,

		);

	$form['spam_detect_composite_consonants_increase'] = array(
				'#title' 					=> t('Consonants: Increase Spamminess Score'),
				'#description' 		=> t('Amount to increase Spam Score for each occurence of 6 consonants or more in a row.  Set to -1 to disable filter.'),
				'#default_value' 	=> variable_get('spam_detect_composite_consonants_increase', 1),
				'#type' 					=> 'textfield',
				'#max_length' 		=> 2,
				'#size'						=> 2,

		);

		$form['spam_detect_composite_first_word_increase'] = array(
				'#title' 					=> t('First Word is Spammy: Increase Spamminess Score'),
				'#description' 		=> t('Amount to increase Spam Score if first word matches value in list.  Set to -1 to disable filter.'),
				'#default_value' 	=> variable_get('spam_detect_composite_first_word_increase', 10),
				'#type' 					=> 'textfield',
				'#max_length' 		=> 2,
				'#size'						=> 2,

		);
	$form['spam_detect_composite_first_word_list'] = array(
      '#type' => 'textarea',
      '#title' => t('First Word is Spammy List'),
      '#description' => t('Enter each test word on a new line'),
      '#default_value' => variable_get('spam_detect_composite_first_word_list', _spam_detect_composite_first_word_list()),
    );

	return system_settings_form($form);

}




